# LayoutSpec


class LayoutSpec
  @ATTACHEDAS_FREEFLOATING: 0
  @ATTACHEDAS_STACK_HORIZONTAL_VERTICALALIGNMENTS_UNDEFINED: 1
  @ATTACHEDAS_STACK_HORIZONTAL_VERTICALALIGNMENTS_STRETCH: 2
  @ATTACHEDAS_STACK_HORIZONTAL_VERTICALALIGNMENTS_TOP: 3
  @ATTACHEDAS_STACK_HORIZONTAL_VERTICALALIGNMENTS_CENTER: 4
  @ATTACHEDAS_STACK_HORIZONTAL_VERTICALALIGNMENTS_BOTTOM: 5

  @STACK_HORIZONTAL_VERTICALALIGNMENTS_UNDEFINED: 6
  @STACK_HORIZONTAL_VERTICALALIGNMENTS_STRETCH: 7
  @STACK_HORIZONTAL_VERTICALALIGNMENTS_TOP: 8
  @STACK_HORIZONTAL_VERTICALALIGNMENTS_CENTER: 9
  @STACK_HORIZONTAL_VERTICALALIGNMENTS_BOTTOM: 10
