# LayoutSpec


class LayoutSpec
  @ATTACHEDAS_FREEFLOATING: 10000
  @ATTACHEDAS_STACK_HORIZONTAL_VERTICALALIGNMENTS_UNDEFINED: 10001
  @ATTACHEDAS_STACK_HORIZONTAL_VERTICALALIGNMENTS_STRETCH: 10002
  @ATTACHEDAS_STACK_HORIZONTAL_VERTICALALIGNMENTS_TOP: 10003
  @ATTACHEDAS_STACK_HORIZONTAL_VERTICALALIGNMENTS_CENTER: 10004
  @ATTACHEDAS_STACK_HORIZONTAL_VERTICALALIGNMENTS_BOTTOM: 10005

  @STACK_HORIZONTAL_VERTICALALIGNMENTS_UNDEFINED: 10006
  @STACK_HORIZONTAL_VERTICALALIGNMENTS_STRETCH: 10007
  @STACK_HORIZONTAL_VERTICALALIGNMENTS_TOP: 10008
  @STACK_HORIZONTAL_VERTICALALIGNMENTS_CENTER: 10009
  @STACK_HORIZONTAL_VERTICALALIGNMENTS_BOTTOM: 10010

  @SPREADABILITY_NONE: 1
  @SPREADABILITY_LOW: 10
  @SPREADABILITY_MEDIUM: 100
  @SPREADABILITY_HIGH: 1000
