# I am a simple LOGO-wise turtle. Note that this widget's graphical
# representation is ONLY the turtle, not the graphics that come
# out of it. The graphics generated by the pen are located in the
# canvas it was attached to when the graphics commands have
# been issued.
#
# example code to run:
#   this.sierpinski(400,40);

class PenWdgt extends Widget
  
  heading: 0
  penSize: nil
  isDown: true
  penPoint: 'tip' # or 'center'
  
  constructor: ->
    super()
    @appearance = new PenAppearance @
    # the arrow (the widget's on-screen representation) is sized at handle
    # scale; @penSize is only the stroke width forward() draws with
    arrowExtent = WorldWdgt.preferencesAndSettings.handleSize * 4
    @_applyExtent new Point arrowExtent, arrowExtent
    @penSize = 1

  _reactToBeingAdded: (whereTo, beingDropped) ->
    if !(whereTo.acceptsPenDrawing?())
      @inform "a pen will only\nwork on a canvas..."

  # PenWdgt access:
  setHeading: (degrees) ->
    @heading = parseFloat(degrees) % 360
    @_changed()
    
  
  # PenWdgt turtle ops:
  turn: (degrees) ->
    @setHeading @heading + parseFloat degrees
  
  forward: (steps) ->
    if !@parent.backBuffer?
      return

    start = @center()
    dist = parseFloat steps
    if dist >= 0
      dest = @position().distanceAngle dist, @heading
    else
      dest = @position().distanceAngle(Math.abs(dist), (@heading - 180))
    @_applyMoveTo dest.round()
    if @isDown
      @parent.drawLine start.subtract(@parent.position()), @center().subtract(@parent.position()), @penSize, @color
  
  down: ->
    @isDown = true
  
  up: ->
    @isDown = false
  
  clear: ->
    if !@parent.backBuffer?
      return
    @parent.clear()
    
  
  # PenWdgt demo ops:
  sierpinski: (length, min) ->
    if length > min
      for i in [0...3]
        @sierpinski length * 0.5, min
        @turn 120
        @forward length
  
  tree: (level, length, angle) ->
    if level > 0
      @penSize = level
      @forward length
      @turn angle
      @tree level - 1, length * 0.75, angle
      @turn angle * -2
      @tree level - 1, length * 0.75, angle
      @turn angle
      @forward -length
